<a href="https://colab.research.google.com/github/Rajesh42/ML_Colab/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Section 1 of:

https://www.udemy.com/deep-learning-prerequisites-the-numpy-stack-in-python/

https://deeplearningcourses.com/c/deep-learning-prerequisites-the-numpy-stack-in-python

## Arrays vs Lists

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
  print(e)

1
2
3


In [5]:
for e in A:
  print(e)

1
2
3


In [6]:
L.append(4)

In [9]:
L

[1, 2, 3, 4]

In [7]:
A.append(4) # doesn't work

AttributeError: ignored

In [10]:
L + [5]

[1, 2, 3, 4, 5]

In [11]:
A + np.array([4])

array([5, 6, 7])

In [12]:
A + np.array([4,5,6])

array([5, 7, 9])

In [13]:
A + np.array([4,5]) # doesn't work

ValueError: ignored

In [14]:
2 * A

array([2, 4, 6])

In [15]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [16]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [17]:
L2 = []
for e in L:
  L2.append(e + 3)

In [18]:
L2

[4, 5, 6, 7]

In [19]:
L2 = [e + 3 for e in L]

In [20]:
L2

[4, 5, 6, 7]

In [21]:
L2 = []
for e in L:
  L2.append(e**2)

In [22]:
L2

[1, 4, 9, 16]

In [23]:
A**2

array([1, 4, 9])

In [24]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [25]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [26]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [27]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

## The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [28]:
a = np.array([1,2])
b = np.array([3,4])

In [29]:
dot = 0
for e, f in zip(a, b):
  dot += e*f
dot

11

In [30]:
# use integer index
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [31]:
a * b

array([3, 8])

In [32]:
np.sum(a * b)

11

In [33]:
(a * b).sum()

11

In [34]:
np.dot(a, b)

11

In [35]:
a.dot(b)

11

In [36]:
b.dot(a)

11

In [37]:
a @ b

11

$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [38]:
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [39]:
amag = np.linalg.norm(amag)
amag

2.23606797749979

In [40]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [41]:
cosangle

0.9838699100999074

In [42]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

## Speed Test

In [43]:
## speed comparison ##
import numpy as np
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 41.035707330644044


## Matrices

In [44]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [45]:
L[0]

[1, 2]

In [46]:
L[0][1]

2

In [47]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [48]:
A[0][1]

2

In [49]:
A[0,1]

2

In [50]:
A[:,0]

array([1, 3])

In [51]:
A.T

array([[1, 3],
       [2, 4]])

In [52]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [53]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [54]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
# error! inner dimensions must match
A.dot(B.T)

ValueError: ignored

In [56]:
np.linalg.det(A)

-2.0000000000000004

In [57]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [58]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [59]:
np.trace(A)

5

In [60]:
np.diag(A)

array([1, 4])

In [61]:
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

In [62]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [63]:
Lam, V = np.linalg.eig(A)

In [64]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [65]:
V[:,0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [66]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [67]:
np.allclose(V @ np.diag(Lam), A @ V)

True

## Solving Linear Systems

In [68]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [69]:
np.linalg.solve(A, b)

array([1500.,  700.])

In [70]:
# don't do this
np.linalg.inv(A).dot(b)

array([1500.,  700.])

## Generating Data

In [71]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [73]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [74]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random()

0.7581150038421872

In [ ]:
np.random.random((2, 3))

array([[0.03284802, 0.83250625, 0.2914984 ],
       [0.03998929, 0.85275735, 0.31078009]])

In [ ]:
np.random.randn(2, 3)

array([[ 0.97730916,  0.05594193, -2.46231718],
       [ 0.75246035, -1.46678342, -0.97568316]])

In [75]:
R = np.random.randn(10000)

In [76]:
R.mean()

-0.0026952437388119304

In [77]:
np.mean(R)

-0.0026952437388119304

In [78]:
R.var()

0.9903438654211503

In [79]:
R = np.random.randn(10000, 3)

In [80]:
R

array([[ 0.05880889,  0.76526439, -2.64630997],
       [ 0.51409559, -0.75326782,  1.16050597],
       [ 0.38797838, -0.74171471,  0.33659726],
       ...,
       [ 1.44108003,  0.13111546, -1.1295562 ],
       [-1.84042294, -1.22743086,  0.79975294],
       [ 0.77220158, -1.32552816,  0.79328036]])

In [81]:
R.mean(axis=0)

array([0.0068157 , 0.00733165, 0.0029633 ])

In [82]:
R.mean(axis=1).shape

(10000,)

In [83]:
np.cov(R).shape

(10000, 10000)

In [84]:
np.cov(R.T)

array([[ 1.00133358e+00, -1.03911500e-03,  4.64098184e-05],
       [-1.03911500e-03,  9.79815762e-01, -1.23349217e-02],
       [ 4.64098184e-05, -1.23349217e-02,  1.00825456e+00]])

In [85]:
np.cov(R, rowvar=False)

array([[ 1.00133358e+00, -1.03911500e-03,  4.64098184e-05],
       [-1.03911500e-03,  9.79815762e-01, -1.23349217e-02],
       [ 4.64098184e-05, -1.23349217e-02,  1.00825456e+00]])

In [86]:
np.random.randint(0, 10, size=(3, 3))

array([[3, 1, 1],
       [9, 2, 5],
       [8, 3, 5]])

In [87]:
np.random.choice(10, size=(3, 3))

array([[7, 8, 4],
       [0, 9, 2],
       [8, 4, 2]])